from pathlib import Path

ROOT_DIR = Path(__file__).parent
FILES_DIR = ROOT_DIR / 'img'
ICON_PATH = FILES_DIR / 'calculadora.png'

# Visual COnfig

BIG_FONT_SIZE = 30
MEDIUM_FONT_SIZE = 25
SMALL_FONT_SIZE = 12
TEXT_MARGIN = 15
MIN_WIDTH = 300

PRIMARY_COLOR = '#1e81b0'
ESCURA_PRIMARY_COLOR = '#16658a'
MAIS_ESCURA_PRIMARY_COLOR = '#115270'
